const puppeteer = require("puppeteer");

(async () => {
  try {
    const browser = await puppeteer.launch({
      headless: "new",
      args: ["--no-sandbox", "--disable-setuid-sandbox"]
    });

    const page = await browser.newPage();

    // Go to InVideo AI
    await page.goto("https://ai.invideo.io", { waitUntil: "networkidle2" });

    console.log("✅ InVideo page opened. Log in manually if prompted...");

    // Wait 30 seconds for manual login
    await page.waitForTimeout(30000);

    // Go to create page
    await page.goto("https://ai.invideo.io/create", { waitUntil: "networkidle2" });

    // Type in your sample script
    await page.keyboard.type("This is a sample TikTok script generated by Aeulin.");

    await page.waitForTimeout(10000); // wait to observe

    await browser.close();
    console.log("✅ Puppeteer script complete.");
  } catch (error) {
    console.error("❌ Puppeteer failed:", error);
  }
})();
