const express = require('express');
const puppeteer = require('puppeteer');

const app = express();
const PORT = process.env.PORT || 3000;

app.get('/', async (req, res) => {
  try {
    const browser = await puppeteer.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();

    await page.goto('https://ai.invideo.io', { waitUntil: 'networkidle2' });
    await page.waitForTimeout(30000); // manual login
    await page.goto('https://ai.invideo.io/create', { waitUntil: 'networkidle2' });
    await page.keyboard.type('This is a sample TikTok script generated by Aeulin.');
    await page.waitForTimeout(10000);

    await browser.close();

    res.send('✅ Puppeteer script executed and browser closed.');
  } catch (error) {
    console.error('❌ Puppeteer failed:', error);
    res.status(500).send('Something went wrong.');
  }
});

app.listen(PORT, () => {
  console.log(`Puppeteer bot running on port ${PORT}`);
});
